### ISSUE TITLE
Items going the edge of the screen

### ISSUE THREAD

**Issue by JudeTejada** [sag1v/react-elastic-carousel#151]
**Is your feature request related to a problem? Please describe.**
Is it possible that when navigating through      items in the next/back button the items would exceed from the page, as currently when navigating through the content it only exceeds from the slider container itself and I was trying to recreate where the items would overexceed from the page when navigating

Sort of like goes around like this
![image](https://user-images.githubusercontent.com/29864561/106585418-4a33e180-6582-11eb-839e-2a34bccc0866.png)

**Comment by sag1v** [comment]
You can achieve this with some CSS. 
Something like:

```css
.rec-carousel {
    position: relative;
}
.rec-slider-container {
    margin: 0;
}
.rec-arrow {
    position: absolute;
    z-index: 999;
}
.rec-arrow-right {
    right: 0;
}
```
